// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ContainerServiceClient is the client API for ContainerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContainerServiceClient interface {
	CreateRootContainer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContainerRootResponse, error)
	CreateContainer(ctx context.Context, in *ContainerCreateRequest, opts ...grpc.CallOption) (*ContainerCreateResponse, error)
	GetContainer(ctx context.Context, in *ContainerGetRequest, opts ...grpc.CallOption) (*ContainerGetResponse, error)
	GetInners(ctx context.Context, in *ContainerGetRequest, opts ...grpc.CallOption) (*ContainerInnersResponse, error)
}

type containerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerServiceClient(cc grpc.ClientConnInterface) ContainerServiceClient {
	return &containerServiceClient{cc}
}

func (c *containerServiceClient) CreateRootContainer(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContainerRootResponse, error) {
	out := new(ContainerRootResponse)
	err := c.cc.Invoke(ctx, "/cyan.ContainerService/CreateRootContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) CreateContainer(ctx context.Context, in *ContainerCreateRequest, opts ...grpc.CallOption) (*ContainerCreateResponse, error) {
	out := new(ContainerCreateResponse)
	err := c.cc.Invoke(ctx, "/cyan.ContainerService/CreateContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) GetContainer(ctx context.Context, in *ContainerGetRequest, opts ...grpc.CallOption) (*ContainerGetResponse, error) {
	out := new(ContainerGetResponse)
	err := c.cc.Invoke(ctx, "/cyan.ContainerService/GetContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) GetInners(ctx context.Context, in *ContainerGetRequest, opts ...grpc.CallOption) (*ContainerInnersResponse, error) {
	out := new(ContainerInnersResponse)
	err := c.cc.Invoke(ctx, "/cyan.ContainerService/GetInners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerServiceServer is the server API for ContainerService service.
// All implementations must embed UnimplementedContainerServiceServer
// for forward compatibility
type ContainerServiceServer interface {
	CreateRootContainer(context.Context, *emptypb.Empty) (*ContainerRootResponse, error)
	CreateContainer(context.Context, *ContainerCreateRequest) (*ContainerCreateResponse, error)
	GetContainer(context.Context, *ContainerGetRequest) (*ContainerGetResponse, error)
	GetInners(context.Context, *ContainerGetRequest) (*ContainerInnersResponse, error)
	mustEmbedUnimplementedContainerServiceServer()
}

// UnimplementedContainerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedContainerServiceServer struct {
}

func (UnimplementedContainerServiceServer) CreateRootContainer(context.Context, *emptypb.Empty) (*ContainerRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRootContainer not implemented")
}
func (UnimplementedContainerServiceServer) CreateContainer(context.Context, *ContainerCreateRequest) (*ContainerCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContainer not implemented")
}
func (UnimplementedContainerServiceServer) GetContainer(context.Context, *ContainerGetRequest) (*ContainerGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContainer not implemented")
}
func (UnimplementedContainerServiceServer) GetInners(context.Context, *ContainerGetRequest) (*ContainerInnersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInners not implemented")
}
func (UnimplementedContainerServiceServer) mustEmbedUnimplementedContainerServiceServer() {}

// UnsafeContainerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerServiceServer will
// result in compilation errors.
type UnsafeContainerServiceServer interface {
	mustEmbedUnimplementedContainerServiceServer()
}

func RegisterContainerServiceServer(s grpc.ServiceRegistrar, srv ContainerServiceServer) {
	s.RegisterService(&ContainerService_ServiceDesc, srv)
}

func _ContainerService_CreateRootContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).CreateRootContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cyan.ContainerService/CreateRootContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).CreateRootContainer(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).CreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cyan.ContainerService/CreateContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).CreateContainer(ctx, req.(*ContainerCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_GetContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).GetContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cyan.ContainerService/GetContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).GetContainer(ctx, req.(*ContainerGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_GetInners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).GetInners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cyan.ContainerService/GetInners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).GetInners(ctx, req.(*ContainerGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContainerService_ServiceDesc is the grpc.ServiceDesc for ContainerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cyan.ContainerService",
	HandlerType: (*ContainerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRootContainer",
			Handler:    _ContainerService_CreateRootContainer_Handler,
		},
		{
			MethodName: "CreateContainer",
			Handler:    _ContainerService_CreateContainer_Handler,
		},
		{
			MethodName: "GetContainer",
			Handler:    _ContainerService_GetContainer_Handler,
		},
		{
			MethodName: "GetInners",
			Handler:    _ContainerService_GetInners_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cyan-api/api/v1/container-service.proto",
}
