// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ContainerServiceClient is the client API for ContainerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContainerServiceClient interface {
	CreateContainer(ctx context.Context, in *ContainerCreateRequest, opts ...grpc.CallOption) (*ContainerCreateResponse, error)
	GetContainers(ctx context.Context, in *ContainerGetRequest, opts ...grpc.CallOption) (*ContainerGetResponse, error)
	UpdateContainer(ctx context.Context, in *ContainerUpdateRequest, opts ...grpc.CallOption) (*ContainerUpdateResponse, error)
	DeleteContainer(ctx context.Context, in *ContainerDeleteRequest, opts ...grpc.CallOption) (*ContainerDeleteResponse, error)
}

type containerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContainerServiceClient(cc grpc.ClientConnInterface) ContainerServiceClient {
	return &containerServiceClient{cc}
}

func (c *containerServiceClient) CreateContainer(ctx context.Context, in *ContainerCreateRequest, opts ...grpc.CallOption) (*ContainerCreateResponse, error) {
	out := new(ContainerCreateResponse)
	err := c.cc.Invoke(ctx, "/cyan.ContainerService/CreateContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) GetContainers(ctx context.Context, in *ContainerGetRequest, opts ...grpc.CallOption) (*ContainerGetResponse, error) {
	out := new(ContainerGetResponse)
	err := c.cc.Invoke(ctx, "/cyan.ContainerService/GetContainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) UpdateContainer(ctx context.Context, in *ContainerUpdateRequest, opts ...grpc.CallOption) (*ContainerUpdateResponse, error) {
	out := new(ContainerUpdateResponse)
	err := c.cc.Invoke(ctx, "/cyan.ContainerService/UpdateContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerServiceClient) DeleteContainer(ctx context.Context, in *ContainerDeleteRequest, opts ...grpc.CallOption) (*ContainerDeleteResponse, error) {
	out := new(ContainerDeleteResponse)
	err := c.cc.Invoke(ctx, "/cyan.ContainerService/DeleteContainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContainerServiceServer is the server API for ContainerService service.
// All implementations must embed UnimplementedContainerServiceServer
// for forward compatibility
type ContainerServiceServer interface {
	CreateContainer(context.Context, *ContainerCreateRequest) (*ContainerCreateResponse, error)
	GetContainers(context.Context, *ContainerGetRequest) (*ContainerGetResponse, error)
	UpdateContainer(context.Context, *ContainerUpdateRequest) (*ContainerUpdateResponse, error)
	DeleteContainer(context.Context, *ContainerDeleteRequest) (*ContainerDeleteResponse, error)
	mustEmbedUnimplementedContainerServiceServer()
}

// UnimplementedContainerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedContainerServiceServer struct {
}

func (UnimplementedContainerServiceServer) CreateContainer(context.Context, *ContainerCreateRequest) (*ContainerCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContainer not implemented")
}
func (UnimplementedContainerServiceServer) GetContainers(context.Context, *ContainerGetRequest) (*ContainerGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContainers not implemented")
}
func (UnimplementedContainerServiceServer) UpdateContainer(context.Context, *ContainerUpdateRequest) (*ContainerUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContainer not implemented")
}
func (UnimplementedContainerServiceServer) DeleteContainer(context.Context, *ContainerDeleteRequest) (*ContainerDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContainer not implemented")
}
func (UnimplementedContainerServiceServer) mustEmbedUnimplementedContainerServiceServer() {}

// UnsafeContainerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContainerServiceServer will
// result in compilation errors.
type UnsafeContainerServiceServer interface {
	mustEmbedUnimplementedContainerServiceServer()
}

func RegisterContainerServiceServer(s grpc.ServiceRegistrar, srv ContainerServiceServer) {
	s.RegisterService(&ContainerService_ServiceDesc, srv)
}

func _ContainerService_CreateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).CreateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cyan.ContainerService/CreateContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).CreateContainer(ctx, req.(*ContainerCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_GetContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).GetContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cyan.ContainerService/GetContainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).GetContainers(ctx, req.(*ContainerGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_UpdateContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).UpdateContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cyan.ContainerService/UpdateContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).UpdateContainer(ctx, req.(*ContainerUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerService_DeleteContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerServiceServer).DeleteContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cyan.ContainerService/DeleteContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerServiceServer).DeleteContainer(ctx, req.(*ContainerDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContainerService_ServiceDesc is the grpc.ServiceDesc for ContainerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContainerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cyan.ContainerService",
	HandlerType: (*ContainerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContainer",
			Handler:    _ContainerService_CreateContainer_Handler,
		},
		{
			MethodName: "GetContainers",
			Handler:    _ContainerService_GetContainers_Handler,
		},
		{
			MethodName: "UpdateContainer",
			Handler:    _ContainerService_UpdateContainer_Handler,
		},
		{
			MethodName: "DeleteContainer",
			Handler:    _ContainerService_DeleteContainer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cyan-api/api/v1/container-service.proto",
}
