// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: cyan-api/api/v1/container-service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContainerRootResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created bool `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *ContainerRootResponse) Reset() {
	*x = ContainerRootResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerRootResponse) ProtoMessage() {}

func (x *ContainerRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerRootResponse.ProtoReflect.Descriptor instead.
func (*ContainerRootResponse) Descriptor() ([]byte, []int) {
	return file_cyan_api_api_v1_container_service_proto_rawDescGZIP(), []int{0}
}

func (x *ContainerRootResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type ContainerCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path      string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Container *Container `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
}

func (x *ContainerCreateRequest) Reset() {
	*x = ContainerCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerCreateRequest) ProtoMessage() {}

func (x *ContainerCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerCreateRequest.ProtoReflect.Descriptor instead.
func (*ContainerCreateRequest) Descriptor() ([]byte, []int) {
	return file_cyan_api_api_v1_container_service_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerCreateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ContainerCreateRequest) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

type ContainerGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ContainerGetRequest) Reset() {
	*x = ContainerGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerGetRequest) ProtoMessage() {}

func (x *ContainerGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerGetRequest.ProtoReflect.Descriptor instead.
func (*ContainerGetRequest) Descriptor() ([]byte, []int) {
	return file_cyan_api_api_v1_container_service_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerGetRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ContainerUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path         string     `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	NewContainer *Container `protobuf:"bytes,2,opt,name=new_container,json=newContainer,proto3" json:"new_container,omitempty"`
}

func (x *ContainerUpdateRequest) Reset() {
	*x = ContainerUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerUpdateRequest) ProtoMessage() {}

func (x *ContainerUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerUpdateRequest.ProtoReflect.Descriptor instead.
func (*ContainerUpdateRequest) Descriptor() ([]byte, []int) {
	return file_cyan_api_api_v1_container_service_proto_rawDescGZIP(), []int{3}
}

func (x *ContainerUpdateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ContainerUpdateRequest) GetNewContainer() *Container {
	if x != nil {
		return x.NewContainer
	}
	return nil
}

type ContainerDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *ContainerDeleteRequest) Reset() {
	*x = ContainerDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerDeleteRequest) ProtoMessage() {}

func (x *ContainerDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerDeleteRequest.ProtoReflect.Descriptor instead.
func (*ContainerDeleteRequest) Descriptor() ([]byte, []int) {
	return file_cyan_api_api_v1_container_service_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerDeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ContainerCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Created   bool       `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Container *Container `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
}

func (x *ContainerCreateResponse) Reset() {
	*x = ContainerCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerCreateResponse) ProtoMessage() {}

func (x *ContainerCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerCreateResponse.ProtoReflect.Descriptor instead.
func (*ContainerCreateResponse) Descriptor() ([]byte, []int) {
	return file_cyan_api_api_v1_container_service_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerCreateResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *ContainerCreateResponse) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

type ContainerGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Container *Container `protobuf:"bytes,1,opt,name=container,proto3" json:"container,omitempty"`
}

func (x *ContainerGetResponse) Reset() {
	*x = ContainerGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerGetResponse) ProtoMessage() {}

func (x *ContainerGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerGetResponse.ProtoReflect.Descriptor instead.
func (*ContainerGetResponse) Descriptor() ([]byte, []int) {
	return file_cyan_api_api_v1_container_service_proto_rawDescGZIP(), []int{6}
}

func (x *ContainerGetResponse) GetContainer() *Container {
	if x != nil {
		return x.Container
	}
	return nil
}

type ContainerUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated      bool       `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	UpdContainer *Container `protobuf:"bytes,2,opt,name=upd_container,json=updContainer,proto3" json:"upd_container,omitempty"`
}

func (x *ContainerUpdateResponse) Reset() {
	*x = ContainerUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerUpdateResponse) ProtoMessage() {}

func (x *ContainerUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerUpdateResponse.ProtoReflect.Descriptor instead.
func (*ContainerUpdateResponse) Descriptor() ([]byte, []int) {
	return file_cyan_api_api_v1_container_service_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerUpdateResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

func (x *ContainerUpdateResponse) GetUpdContainer() *Container {
	if x != nil {
		return x.UpdContainer
	}
	return nil
}

type ContainerDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Deleted bool `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
}

func (x *ContainerDeleteResponse) Reset() {
	*x = ContainerDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerDeleteResponse) ProtoMessage() {}

func (x *ContainerDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerDeleteResponse.ProtoReflect.Descriptor instead.
func (*ContainerDeleteResponse) Descriptor() ([]byte, []int) {
	return file_cyan_api_api_v1_container_service_proto_rawDescGZIP(), []int{8}
}

func (x *ContainerDeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ContainerInnersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inners []*Container `protobuf:"bytes,1,rep,name=inners,proto3" json:"inners,omitempty"`
}

func (x *ContainerInnersResponse) Reset() {
	*x = ContainerInnersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerInnersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInnersResponse) ProtoMessage() {}

func (x *ContainerInnersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInnersResponse.ProtoReflect.Descriptor instead.
func (*ContainerInnersResponse) Descriptor() ([]byte, []int) {
	return file_cyan_api_api_v1_container_service_proto_rawDescGZIP(), []int{9}
}

func (x *ContainerInnersResponse) GetInners() []*Container {
	if x != nil {
		return x.Inners
	}
	return nil
}

type Container struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsLeaf   bool              `protobuf:"varint,2,opt,name=is_leaf,json=isLeaf,proto3" json:"is_leaf,omitempty"`
	MetaData map[string]string `protobuf:"bytes,3,rep,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Container) Reset() {
	*x = Container{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_cyan_api_api_v1_container_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_cyan_api_api_v1_container_service_proto_rawDescGZIP(), []int{10}
}

func (x *Container) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Container) GetIsLeaf() bool {
	if x != nil {
		return x.IsLeaf
	}
	return false
}

func (x *Container) GetMetaData() map[string]string {
	if x != nil {
		return x.MetaData
	}
	return nil
}

var File_cyan_api_api_v1_container_service_proto protoreflect.FileDescriptor

var file_cyan_api_api_v1_container_service_proto_rawDesc = []byte{
	0x0a, 0x27, 0x63, 0x79, 0x61, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2d, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x63, 0x79, 0x61, 0x6e, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x15,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22,
	0x5b, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x2d, 0x0a,
	0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x63, 0x79, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x22, 0x29, 0x0a, 0x13,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x62, 0x0a, 0x16, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x34, 0x0a, 0x0d, 0x6e, 0x65, 0x77, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63,
	0x79, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x0c, 0x6e,
	0x65, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x22, 0x2c, 0x0a, 0x16, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x62, 0x0a, 0x17, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2d,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x79, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x22, 0x45, 0x0a,
	0x14, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x79, 0x61, 0x6e, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x22, 0x69, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x0d, 0x75, 0x70, 0x64,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x63, 0x79, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x52, 0x0c, 0x75, 0x70, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x22,
	0x33, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x22, 0x42, 0x0a, 0x17, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x27, 0x0a, 0x06, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x63, 0x79, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x52, 0x06, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x22, 0xb1, 0x01, 0x0a, 0x09, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73,
	0x5f, 0x6c, 0x65, 0x61, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4c,
	0x65, 0x61, 0x66, 0x12, 0x3a, 0x0a, 0x09, 0x6d, 0x65, 0x74, 0x61, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x79, 0x61, 0x6e, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x1a,
	0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xc4, 0x02, 0x0a,
	0x10, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4c, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x1b, 0x2e, 0x63, 0x79, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x52, 0x6f, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x50, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x12, 0x1c, 0x2e, 0x63, 0x79, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x63, 0x79, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x47, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x12, 0x19, 0x2e, 0x63, 0x79, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x63,
	0x79, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x19, 0x2e, 0x63, 0x79, 0x61, 0x6e, 0x2e, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x63, 0x79, 0x61, 0x6e, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x13, 0x5a, 0x11, 0x63, 0x79, 0x61, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cyan_api_api_v1_container_service_proto_rawDescOnce sync.Once
	file_cyan_api_api_v1_container_service_proto_rawDescData = file_cyan_api_api_v1_container_service_proto_rawDesc
)

func file_cyan_api_api_v1_container_service_proto_rawDescGZIP() []byte {
	file_cyan_api_api_v1_container_service_proto_rawDescOnce.Do(func() {
		file_cyan_api_api_v1_container_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_cyan_api_api_v1_container_service_proto_rawDescData)
	})
	return file_cyan_api_api_v1_container_service_proto_rawDescData
}

var file_cyan_api_api_v1_container_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_cyan_api_api_v1_container_service_proto_goTypes = []interface{}{
	(*ContainerRootResponse)(nil),   // 0: cyan.ContainerRootResponse
	(*ContainerCreateRequest)(nil),  // 1: cyan.ContainerCreateRequest
	(*ContainerGetRequest)(nil),     // 2: cyan.ContainerGetRequest
	(*ContainerUpdateRequest)(nil),  // 3: cyan.ContainerUpdateRequest
	(*ContainerDeleteRequest)(nil),  // 4: cyan.ContainerDeleteRequest
	(*ContainerCreateResponse)(nil), // 5: cyan.ContainerCreateResponse
	(*ContainerGetResponse)(nil),    // 6: cyan.ContainerGetResponse
	(*ContainerUpdateResponse)(nil), // 7: cyan.ContainerUpdateResponse
	(*ContainerDeleteResponse)(nil), // 8: cyan.ContainerDeleteResponse
	(*ContainerInnersResponse)(nil), // 9: cyan.ContainerInnersResponse
	(*Container)(nil),               // 10: cyan.Container
	nil,                             // 11: cyan.Container.MetaDataEntry
	(*emptypb.Empty)(nil),           // 12: google.protobuf.Empty
}
var file_cyan_api_api_v1_container_service_proto_depIdxs = []int32{
	10, // 0: cyan.ContainerCreateRequest.container:type_name -> cyan.Container
	10, // 1: cyan.ContainerUpdateRequest.new_container:type_name -> cyan.Container
	10, // 2: cyan.ContainerCreateResponse.container:type_name -> cyan.Container
	10, // 3: cyan.ContainerGetResponse.container:type_name -> cyan.Container
	10, // 4: cyan.ContainerUpdateResponse.upd_container:type_name -> cyan.Container
	10, // 5: cyan.ContainerInnersResponse.inners:type_name -> cyan.Container
	11, // 6: cyan.Container.meta_data:type_name -> cyan.Container.MetaDataEntry
	12, // 7: cyan.ContainerService.CreateRootContainer:input_type -> google.protobuf.Empty
	1,  // 8: cyan.ContainerService.CreateContainer:input_type -> cyan.ContainerCreateRequest
	2,  // 9: cyan.ContainerService.GetContainer:input_type -> cyan.ContainerGetRequest
	2,  // 10: cyan.ContainerService.GetInners:input_type -> cyan.ContainerGetRequest
	0,  // 11: cyan.ContainerService.CreateRootContainer:output_type -> cyan.ContainerRootResponse
	5,  // 12: cyan.ContainerService.CreateContainer:output_type -> cyan.ContainerCreateResponse
	6,  // 13: cyan.ContainerService.GetContainer:output_type -> cyan.ContainerGetResponse
	9,  // 14: cyan.ContainerService.GetInners:output_type -> cyan.ContainerInnersResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_cyan_api_api_v1_container_service_proto_init() }
func file_cyan_api_api_v1_container_service_proto_init() {
	if File_cyan_api_api_v1_container_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cyan_api_api_v1_container_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerRootResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cyan_api_api_v1_container_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cyan_api_api_v1_container_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cyan_api_api_v1_container_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cyan_api_api_v1_container_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cyan_api_api_v1_container_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cyan_api_api_v1_container_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cyan_api_api_v1_container_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cyan_api_api_v1_container_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cyan_api_api_v1_container_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerInnersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cyan_api_api_v1_container_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Container); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cyan_api_api_v1_container_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cyan_api_api_v1_container_service_proto_goTypes,
		DependencyIndexes: file_cyan_api_api_v1_container_service_proto_depIdxs,
		MessageInfos:      file_cyan_api_api_v1_container_service_proto_msgTypes,
	}.Build()
	File_cyan_api_api_v1_container_service_proto = out.File
	file_cyan_api_api_v1_container_service_proto_rawDesc = nil
	file_cyan_api_api_v1_container_service_proto_goTypes = nil
	file_cyan_api_api_v1_container_service_proto_depIdxs = nil
}
